[project]
name = "ferriai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "keras-ocr>=0.9.3",
    "numpy>=2.2.4",
    "opencv-python>=4.11.0.86",
    "uvicorn>=0.34.0",
]
